resources:
- ../../base

images:
- name: thangsu/devops-lab
  newName: thangsu/devops-lab
  newTag: staging-25c3606

replicas:
- count: 1
  name: dev-app

namespace: new-staging

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
