resources:
- ../../base
# enable ingress component
components:
- ../../base/components/ingress

# set namespace
namespace: new-staging

images:
- name: thangsu/devops-lab
  newName: thangsu/devops-lab
  newTag: staging-15cd71c

replicas:
- count: 1
  name: dev-app

# set domain for ingress
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/initContainers/0/command
      value:
        - "sh"
        - "-c"
        - "until nslookup dev-mysql-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;"
  target:
    kind: Deployment
    name: dev-app
- patch: |-
    - op: replace
      path: /spec/template/spec/initContainers/1/command
      value:
        - "sh"
        - "-c"
        - "until nslookup dev-memcached-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;"
  target:
    kind: Deployment
    name: dev-app
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.kameyoko.online
  target:
    kind: Ingress
    name: devops-ingress


# create secret for storing password of mysql and rabbitmq
secretGenerator:
- literals:
  - db-pass=thang2k3003
  - rmq-pass=thang2k3003
  name: dev-app-secret

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
