resources: 
  - ../../base

namespace: new-prod
images:
- name: thangsu/devops-lab
  newName: thangsu/devops-lab
  newTag: main-40aa67c

patches: 
- target: 
    kind: Deployment 
    name: dev-app
  path: app-deploy-patch.yml
- target: 
    kind: Ingress
    name: devops-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: prod.kameyoko.online
replicas:
- count: 1
  name: dev-app